### ISSUE TITLE
MorseBase ain't working

### ISSUE THREAD

**Issue by ace-tronaut** [ace-tronaut/MorseL#6]
So Big F the base is not working, the **\n** is not being identified within a list. I did the **\n** outside the list in a string and it worked but put it in a list and suddenly it goes _dumb_. 
[Look](https://i.ibb.co/86kZFKv/image.png)

**Comment by johnsonjmaliakal** [comment]
So all we have to do is call the element in the list which represents the ASCII art. This can be done by:
`for i in l:`
or
`for i in range (len(l)): \n
    for j in i:`
